#!/usr/bin/env python3
"""
Simple fill report: what regime-aa asked for vs what the pipeline now carries.

Reads regime-aa-indicator-coverage.csv and prints a readable request -> fill
map: every requested (indicator x region) slot, its status, and the concrete
pipeline ticker(s)/id(s) that now satisfy it. Output: regime-aa-fill-report.md.
"""
import csv
import os
from collections import Counter

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
CSV = os.path.join(OUT_DIR, "regime-aa-indicator-coverage.csv")

COVERED, PARTIAL = "Covered", "Partial"
SOURCEABLE, HARD = "Missing-Sourceable", "Missing-Hard"


def esc(s):
    return (s or "").replace("|", "\\|")


def main():
    rows = list(csv.DictReader(open(CSV)))
    n = len(rows)
    counts = Counter(r["status"] for r in rows)

    lines = []
    lines.append("# Regime-AA Request → Pipeline Fill Report")
    lines.append("")
    lines.append("What the regime-aa process asked for (`regime-aa-indicator-req.md` §5, "
                 "one row per indicator × region) against the ticker/series the data "
                 "pipeline now carries. Generated by `build_fill_report.py`.")
    lines.append("")
    filled = counts[COVERED]
    lines.append(f"**{filled} of {n} requested slots filled** "
                 f"({100*filled//n}%). Partial {counts[PARTIAL]}, "
                 f"sourceable-but-not-yet-filled {counts[SOURCEABLE]}, "
                 f"hard/proprietary {counts[HARD]}.")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|---|---|")
    for s in (COVERED, PARTIAL, SOURCEABLE, HARD):
        lines.append(f"| {s} | {counts.get(s,0)} |")
    lines.append(f"| **Total** | **{n}** |")
    lines.append("")

    sections = [
        (COVERED, "✅ Filled in the pipeline",
         "Pipeline carries the series (or a direct derivation) for this slot."),
        (PARTIAL, "🟡 Partially filled",
         "A proxy / related series is present, or only part of the regional breadth."),
        (SOURCEABLE, "⬜ Not yet filled — free source identified",
         "A free/public source exists; not yet in the pipeline."),
        (HARD, "⛔ Not filled — hard / proprietary",
         "Only proprietary, or no reliable free source."),
    ]

    for status, title, blurb in sections:
        sel = [r for r in rows if r["status"] == status]
        lines.append(f"## {title} ({len(sel)})")
        lines.append("")
        lines.append(f"_{blurb}_")
        lines.append("")
        if status in (COVERED, PARTIAL):
            lines.append("| Indicator | Region | Pipeline ticker / id | Source |")
            lines.append("|---|---|---|---|")
            for r in sel:
                lines.append(f"| {esc(r['indicator'])} | {r['region']} | "
                             f"{esc(r['pipeline_match']) or '—'} | {esc(r['pipeline_source'])} |")
        else:
            lines.append("| Indicator | Region | Candidate source / why blocked |")
            lines.append("|---|---|---|")
            for r in sel:
                lines.append(f"| {esc(r['indicator'])} | {r['region']} | "
                             f"{esc(r['candidate_free_source']) or esc(r['notes'])} |")
        lines.append("")

    out = os.path.join(OUT_DIR, "regime-aa-fill-report.md")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out} ({filled}/{n} filled)")


if __name__ == "__main__":
    main()
