# 5. The Regime Indicator Library

This section is the structured candidate library of regime indicators that the master plan's regime engine uses as input. The library is organised across the four pillars that drive the four-quadrant macro classification — Growth, Inflation, Financial Conditions, Monetary Policy — and across the cycle-timing tiers that distinguish forward-looking, contemporaneous, and backward-looking signals. Each indicator is documented with its source, frequency, publication lag, and interpretive convention.

Three points before the catalogue itself.

First, every indicator in this library is a *candidate*. The library is the pool from which the production regime engine is built. No indicator earns a place in production until it has passed the validation framework specified in Section 8B against the historical regime label series produced in Phase 1 of the master forward plan. The cycle-timing tag (Leading / Coincident / Lagging) attached to each indicator below is the literature-derived prior; the production cycle-timing classification is the *output* of validation, not the input. Indicators that the literature classifies as Leading but that fail the Section 8B lead-time test in our hands are reclassified or removed.

Second, the library has three distinct sources of supply. The first is the *literature-derived structured library* (this section's principal content): the indicators repeatedly cited in the academic and practitioner literature on regime-based allocation, organised here under the four-pillar framework. The second is the *92 composite indicators already produced by the data pipeline*: each carries a 156-week rolling z-score, a regime classification, a forward-regime signal, and a cycle-timing tag (90 of the 92 are tagged Leading, 2 Coincident; full inventory in the data pipeline's `manuals/indicator_manual.md`). These pipeline composites enter the candidate pool on equal footing with the literature indicators. The third is the *long-run historical data layer* documented in `longrun_assetclass_data_sources.md`: not indicators in their own right, but the multi-decade history that makes the validation work feasible — the OECD Main Economic Indicators feed via FRED for monthly multi-country equity prices and 10-year sovereign yields back to 1957, Robert Shiller's monthly US series back to 1871, the Kenneth French data library back to 1926, the IMF Primary Commodity Prices monthly back to 1960, the Bank of England Millennium dataset for UK rates, and the Jordà–Schularick–Taylor annual macrohistory dataset for 18 advanced economies back to 1870.

Third, the library is per-region. Each indicator's regional applicability is documented. Some indicators are inherently national (the Federal Funds Rate; UK Bank Rate); some are inherently global (the Bloomberg Commodity Index; gold price); some have regional analogues (PMI, CPI, yield-curve slope) that are consumed in parallel across the priority five regions of the first build (US, UK, Eurozone, Japan, China). Where a regional analogue exists but is unavailable from a free source, the gap is noted explicitly; Phase 0 (master plan §17.2) resolves the gap formally.

### Accepted-gap annotations (consumer/pipeline contract)

§5 is the canonical statement of what regime-aa needs the pipeline to supply. The Phase 0 coverage check (`scripts/phase_0_coverage_check.py`) reads this section, matches each row's indicator name and regional analogues against the pipeline's `data/macro_indicator_library.csv` and `data/macro_economic.csv`, and reports gaps. Each gap auto-templates a cross-repo request memo for the pipeline.

Where the upstream data genuinely cannot be supplied for a particular region — typically because no free source carries it (e.g. CN 10-year sovereign yield) — the indicator's row in the table below is annotated inline `[accepted gap: <one-line workaround>]`. The coverage check reads the annotation and silences the memo; the row moves from "missing" to "accepted gap" in the report. The annotation is the durable record of the workaround.

The catalogue proceeds pillar by pillar.

## 5.1 Growth Indicators

Growth indicators measure the direction and momentum of real economic activity. They drive the horizontal axis of the four-quadrant regime call. The literature distinguishes three tiers within Growth: forward-looking / anticipatory indicators (Tier 1–2) that lead the macro outturn by 6–18 months; business-cycle confirmers (Tier 3) that move contemporaneously with activity; and real-time gauges (Tier 3–4) that fill the gap between forward signals and the lagged official statistics. The master plan's per-region framework requires regional analogues of the most important Tier 1–3 indicators for each of the priority five regions; the catalogue below lists the US-centric primary indicators with regional analogues noted.

### 5.1.1 Forward-Looking / Anticipatory (Tier 1–2)

| Indicator                               | Source / Frequency             | Lag        | Regional analogues                                | Interpretation                                                                                                                                                                          |
|-----------------------------------------|--------------------------------|------------|---------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Yield Curve (10y minus 2y)              | FRED / daily                   | Real-time  | UK (gilts), DE (bunds), JP (JGBs), CN (CGBs)      | Inversion has preceded every US recession with 6–18 month lead. Below zero is recession-watch; below −75bps is extreme. Direction of change is informative as well as level.            |
| Yield Curve (10y minus 3m)              | FRED / daily                   | Real-time  | UK, DE, JP                                        | Alternative slope. Some research (Campbell & Shiller) judges the 10y–3m a more reliable near-term recession predictor than the 10y–2y.                                                  |
| OECD Composite Leading Indicator (CLI)  | OECD / monthly                 | 5–6 weeks  | All five priority regions plus EM aggregate      | CLI > 100 and rising = expansion; < 100 and falling = contraction. Designed to lead industrial production by 6–9 months. Direction of change more informative than level.              |
| Conference Board LEI (US)               | Conference Board / monthly     | 3–4 weeks  | UK, DE (separate national LEIs); none for Asia   | Composite of 10 sub-indicators. Three consecutive monthly declines of the 6-month diffusion index is a reliable recession signal.                                                       |
| M2 Money Supply (YoY%)                  | Federal Reserve / monthly      | 4–6 weeks  | UK (M4), Eurozone (M3), JP (M2), CN (M2)         | M2 growth leads nominal GDP growth by 12–18 months. Sustained YoY deceleration below zero (as 2022–2023) signals deflationary pressure with long lead.                                  |
| NAHB Housing Market Index               | NAHB / monthly                 | Mid-month  | UK (RICS Housing Survey), DE (ifo Construction)  | Housing is the most interest-rate-sensitive sector. Below 50 and falling typically precedes broader weakness by 6–12 months. A strong leading indicator of the credit cycle.            |
| Building Permits (SAAR)                 | Census Bureau / monthly        | 4 weeks    | UK ONS housing permits, DE Bauanträge            | Component of the LEI. Leads housing starts by 1–2 months. YoY rate of change more informative than absolute level.                                                                       |
| Senior Loan Officer Survey (SLOOS)      | Federal Reserve / quarterly    | Quarterly  | UK Bank of England Credit Conditions Survey, ECB Bank Lending Survey, BoJ Tankan financial conditions | Net percentage of banks tightening lending standards. The most reliable indicator of credit-cycle turning points. Net tightening > 20% has preceded every recession. 6–12 month lead.   |

### 5.1.2 Business-Cycle Confirmers (Tier 3)

| Indicator                              | Source / Frequency           | Lag                | Regional analogues                                                                | Interpretation                                                                                                                                            |
|----------------------------------------|------------------------------|--------------------|-----------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|
| ISM Manufacturing PMI                  | ISM / monthly                | 1st business day   | UK PMI, Eurozone Manufacturing PMI, China Caixin / NBS PMI, Japan Tankan          | 50 is the expansion / contraction boundary. New Orders sub-index leads the headline by 1–2 months. < 45 signals significant contraction.                  |
| ISM New Orders − Inventories           | ISM (calculated)             | 1st business day   | UK, Eurozone (where sub-indices available)                                        | Spread between New Orders and Inventories is a powerful leading indicator of future PMI direction. Often leads headline PMI by 2–3 months.                |
| JP Morgan Global Manufacturing PMI     | JP Morgan / S&P / monthly    | 1st business day   | Global aggregate                                                                  | The single best indicator for a global multi-asset portfolio's growth axis. R² > 60% with directional global equity returns.                              |
| ISM Services PMI (NMI)                 | ISM / monthly                | 3rd business day   | UK Services PMI, Eurozone Services PMI                                            | Services sector dominates US GDP. Above 50 with New Orders rising is a strong expansion signal. Cross-check against Manufacturing for cycle consistency.   |
| Philadelphia Fed Manufacturing Survey  | Philadelphia Fed / monthly   | 3rd Thursday       | None                                                                              | Earlier publication than ISM provides preview signal. High correlation with ISM. Prices Paid component is an early inflation indicator.                    |
| Empire State Manufacturing Survey      | NY Fed / monthly             | 2nd Monday         | None                                                                              | First major monthly manufacturing survey of the month. High noise-to-signal ratio but earliest glimpse.                                                    |
| Consumer Confidence (Conference Board) | Conference Board / monthly   | Last Tuesday       | UK GfK Consumer Confidence, Eurozone EU Consumer Confidence, JP Cabinet Office     | Present Situation and Expectations components. Sharp divergence (present high, expectations falling) is a recession warning. 2–3 month lead on spending.   |
| Initial Jobless Claims                 | Department of Labor / weekly | Thursday           | UK ONS claimant count (monthly), DE / FR / IT unemployment claims (varying)       | Weekly frequency makes this real-time. 4-week MA preferred to smooth volatility. Sustained rise above 300k (non-crisis) signals labour-market deterioration. |

### 5.1.3 Coincident Real-Time Gauges (Tier 3–4)

| Indicator                       | Source / Frequency               | Lag        | Regional analogues                                       | Interpretation                                                                                                                                  |
|---------------------------------|----------------------------------|------------|----------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------|
| Nonfarm Payrolls (MoM change)  | BLS / monthly                    | 1st Friday | UK ONS payroll, DE / FR employment, JP employment        | 3-month average > 200k = solid expansion; < 100k = slowdown; negative = recession. Coincident: confirms what leading indicators already predicted. |
| Industrial Production (YoY%)   | Federal Reserve / monthly        | ~2 weeks   | UK ONS IoP, Eurozone Eurostat IPI, JP METI IIP, CN NBS   | Hard output data that cross-checks PMI surveys. YoY negative growth is a recession signal. Capacity utilisation is a companion inflation gauge.    |
| Retail Sales (MoM%, ex autos)  | Census Bureau / monthly          | ~2 weeks   | UK ONS, Eurozone Eurostat retail trade, JP METI         | Consumer spending momentum. Ex-autos removes volatility. Real (deflated) YoY < 0% is recessionary.                                              |
| Real GDP (advance estimate)    | BEA / quarterly                  | ~4 weeks   | UK ONS, Eurozone Eurostat, JP Cabinet Office, CN NBS    | Definitive growth measure, highly lagged. Two consecutive negative quarters = technical recession. Treat advance estimate as directional only.   |
| Atlanta Fed GDPNow             | Atlanta Fed / continuous         | Real-time  | UK ONS monthly GDP, Eurozone CEPR Eurocoin              | Real-time GDP estimate using high-frequency components. Volatile but useful for intra-quarter regime monitoring.                                |
| Chicago Fed NFCI               | Chicago Fed / weekly             | Friday     | UK BoE FCI; Eurozone ECB CISS; no clean JP / CN analogue | National Financial Conditions Index. Negative = looser-than-average; positive and rising = tightening, leads growth deceleration.               |

### 5.1.4 Pipeline Composite Candidates (Growth-Pillar Tagged)

The data pipeline's 92 composite indicators include a substantial set tagged with the Growth concept and / or with a Growth-relevant cycle-timing classification. These enter the Section 8B validation alongside the literature indicators above. A non-exhaustive selection — the full inventory is in the data pipeline's indicator library — includes: US_G1 (Cyclicals vs Defensives, XLY/XLP log-ratio, regime-classified at z = ±1); US_G2, US_G3, US_G4, US_G5 (banks vs utilities, tech leadership, market breadth); US_CA_G1 (SPY vs GOVT cross-asset risk-on/off); FX_CMD1 (Copper / Gold ratio, the global growth barometer); GL_PMI1 (equal-weight Global Manufacturing Survey Composite, the free-data JP Morgan Global PMI substitute); GL_CLI1, GL_CLI2, GL_CLI5, EU_CLI1, AS_CLI1 (CLI differentials and breadth across regions); the regional macro / survey composites (US_JOBS1, US_JOBS2, US_JOBS3 for labour; US_HOUS1 for housing; US_M2 for liquidity; US_ISM1 for ISM aggregate). All are submitted to validation. The signature characteristic of the pipeline composites — their use of 156-week rolling z-scores against their own history — is consistent with the normalisation step of the per-region pillar score in Section 3.5.

### 5.1.5 Long-Run Data Layer for the Growth Axis

For the validation work, the candidate Growth indicators must be evaluable against historical regime labels going back as far as the data supports. The long-run data layer that makes this feasible:

- **OECD Main Economic Indicators feed via FRED.** Monthly equity share-price indices (`SPASTT01{ISO}M661N`) and 10-year sovereign yields (`IRLTLT01{ISO}M156N`) for the priority regions back to January 1957, with consistent OECD methodology. This is the primary multi-country monthly source for the Growth axis: equity returns and yield-curve slopes are computed directly from the panel.
- **FRED native US series.** US 3-month T-bill rate (`TB3MS`) monthly back to 1934; US 10-year Treasury (`GS10`) monthly back to 1953; US Industrial Production (`INDPRO`) monthly back to 1919; US unemployment (`UNRATE`) monthly back to 1948; NBER recession indicator (`USREC`) monthly back to 1854. These extend the US-specific Growth-axis history substantially earlier than the OECD multi-country panel.
- **Robert Shiller monthly US series back to 1871.** S&P 500 price + dividends + earnings, US CPI, long-term US interest rate. The deepest US history available; the source for the US-specific pre-1957 anchor.
- **Bank of England Millennium dataset.** UK rates and inflation back to the 1700s. Available as Excel and partially mirrored on FRED. Extends UK Growth-axis history materially.
- **Jordà–Schularick–Taylor Macrohistory database.** Annual data for 18 advanced economies from 1870. Annual frequency only; used for cross-validation of regime labels and for pre-1957 anchor where monthly data is unavailable.

The data-availability test in Phase 0 of the master forward plan ingests this layer, validates retrievability against the catalogue claims (some of which have not yet been tested in our hands), and produces the per-region availability matrix that determines what regional regime modelling can support.

## 5.2 Inflation Indicators

Inflation indicators measure the direction and momentum of price-level changes. They drive the vertical axis of the four-quadrant regime call. The pillar covers official inflation statistics (CPI, PCE, PPI), market-implied inflation expectations (TIPS breakevens, inflation swaps), survey-based inflation expectations (University of Michigan, central-bank expectations surveys), and inflation-adjacent commodity / supply-chain indicators (oil, CRB Raw Industrials, ISM Prices Paid).

| Indicator                                           | Source / Frequency           | Lag             | Regional analogues                                                       | Interpretation                                                                                                                                                       |
|-----------------------------------------------------|------------------------------|-----------------|--------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| CPI Headline (YoY%)                                 | BLS / monthly                | ~2 weeks        | UK ONS CPI, Eurozone Eurostat HICP, JP MIC CPI, CN NBS CPI               | Primary public inflation benchmark. Above 5% YoY used by Bouyé and Teiletche to define high-inflation regimes. Direction and momentum more important than level.    |
| Core CPI (ex food & energy)                         | BLS / monthly                | ~2 weeks        | UK / EZ / JP / CN core measures                                          | Strips transitory commodity price effects. Better signal of underlying inflation. Sticky above 3% = overheating; below 2% = disinflationary.                          |
| PCE Deflator (Core)                                 | BEA / monthly                | ~5 weeks        | None (US-specific Fed measure)                                            | Fed's preferred measure. Differs from Core CPI in housing weight and healthcare. Generally 20–40 bps below Core CPI. Fed 2% target refers to this measure.            |
| Trimmed Mean / Median CPI                           | Cleveland / Dallas Fed       | ~2 weeks        | None                                                                      | Removes extreme positive and negative monthly price changes to isolate underlying inflation momentum. Less volatile than headline; better trend indicator.            |
| PPI Final Demand (YoY%)                             | BLS / monthly                | ~2 weeks        | UK ONS PPI, Eurozone Eurostat PPI, JP BoJ PPI, CN NBS PPI                | Producer prices lead consumer prices by 2–3 months. PPI acceleration is a leading indicator of CPI pressure. Useful for input-cost inflation.                          |
| TIPS 5-year Breakeven Rate                          | FRED / daily                 | Real-time       | UK linker breakeven; Eurozone OAT€i / Bund€i breakevens                  | Market-implied 5-year average inflation. Real-time and forward-looking. > 3% = inflation concern; direction of change signals shifting expectations.                  |
| TIPS 10-year Breakeven Rate                         | FRED / daily                 | Real-time       | UK 10y breakeven, EZ 10y inflation swap, JP 10y                          | The most widely watched breakeven. Cross-check against 5y breakeven: rising 5y relative to 10y = near-term inflation concerns dominant.                                |
| 5y5y Forward Inflation Swap                         | Bloomberg / daily            | Real-time       | UK / EZ / JP equivalents                                                 | Market-implied inflation for years 5–10 in the future. Strips current-cycle dynamics; measures whether long-run expectations are anchored. Critical Fed monitor.       |
| University of Michigan Inflation Expectations (5–10y) | Univ. Michigan / monthly  | Mid-month prelim | UK BoE Inflation Attitudes Survey, EZ ECB Survey of Consumer Expectations | Consumer-based long-term inflation expectations. Fed watches as anchored / unanchored signal. Rise above 3.5% would be a policy alarm.                                 |
| ISM / PMI Prices Paid                               | ISM / monthly                | 1st business day | UK PMI Prices Paid, EZ PMI Prices Paid                                   | Sub-index of ISM Manufacturing. Leads producer and consumer prices. > 60 = accelerating input cost; < 40 = deflationary inputs.                                       |
| CRB Raw Industrials Index                           | Bloomberg / daily            | Real-time       | None (global proxy)                                                       | Commodity price index for industrial raw materials (ex-energy). Leads PPI by 1–2 months. Rising = early inflation warning, especially in early-cycle overheating.      |
| Brent Crude Oil Price                               | Bloomberg / daily            | Real-time       | None (global)                                                             | Oil is both inflation input and global growth indicator. Rising oil + rising PMIs = overheating; rising oil + falling PMIs = stagflation; falling both = downturn.    |

### 5.2.1 Pipeline Composite Candidates (Inflation-Pillar Tagged)

The data pipeline's existing inflation-tagged composites are notably thin: only US_R4 (US TIPS 10-year breakeven z-score) and UK_R2 (UK breakeven equivalent) carry the Inflation concept tag in the production library. Phase 0 / Phase 1 of the master forward plan adds per-region inflation composites that the pipeline currently lacks: US_INFL1 (CPI YoY z-score + Core PCE YoY z-score + 5y5y forward inflation expectation, output regime classification: high / above-target / on-target / below-target / disinflationary), UK_INFL1 (UK CPI YoY + UK breakeven), EU_INFL1 (HICP YoY + 5y5y forward inflation expectation), JP_INFL1 (Core CPI YoY + JP breakevens where available), CN_INFL1 (CPI YoY + PPI YoY composite). These are pure-derived Phase E composites that consume series already in the data pipeline; the addition is a calculator function plus a row in the indicator library, not a new fetcher.

### 5.2.2 Long-Run Data Layer for the Inflation Axis

- **FRED native series.** US CPI all-urban (`CPIAUCSL`) monthly back to 1947; US PPI monthly back to 1947; US PCE deflator monthly back to 1959. These provide the deepest US inflation history.
- **Shiller monthly CPI back to 1871.** Mirrors the US CPI work but with the structural break at 1947 when official BLS methodology changed.
- **OECD MEI inflation series via FRED.** Monthly CPI for the priority regions from various dates in the 1950s–1960s; coverage varies by country.
- **JST Macrohistory.** Annual CPI for 18 advanced economies back to 1870. Cross-validation source for regime-period inflation labels.
- **TIPS breakevens.** Available from 1997 in the US; UK linkers from 1981; Eurozone inflation swaps from the early 2000s. The shortest of the inflation-axis histories; insufficient for long-history regime training but valuable as a real-time forward-inflation signal.

## 5.3 Financial Conditions Indicators

Financial conditions indicators measure the cost and availability of capital across asset classes. They are not themselves Growth or Inflation indicators, but they modulate confidence in the four-quadrant call (a Goldilocks call accompanied by tightening financial conditions is materially less robust than the same call with loose conditions) and they drive several of the supplementary signals used by Frameworks A, B, and C in Section 16.

| Indicator                                     | Source / Frequency             | Lag       | Regional analogues                                                  | Interpretation                                                                                                                                                |
|-----------------------------------------------|--------------------------------|-----------|---------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|
| HY Credit Spreads (ICE BofA OAS)              | FRED / daily                   | Real-time | UK / EZ / Asia HY analogues (where available)                       | Single most important financial-conditions variable. > 600 bps = severe stress; > 800 bps = crisis. Rising spreads lead downturns by 2–6 months.               |
| IG Credit Spreads (OAS)                       | FRED / daily                   | Real-time | UK / EZ / JP / CN IG analogues                                       | Broader and more stable than HY. > 200 bps has historically coincided with recessions. The IG–HY spread ratio measures within-credit risk appetite.            |
| VIX (CBOE Volatility Index)                   | CBOE / daily                   | Real-time | UK / EZ / Asian VIX-style measures                                   | Equity implied volatility. > 30 = stress; > 40 = crisis territory. Coincident, not leading: confirms regime transitions rather than anticipating.              |
| MOVE Index (US Treasury Volatility)           | Bloomberg / daily              | Real-time | UK / EZ / JP equivalents (less developed markets)                   | Fixed-income analogue of VIX. Elevated MOVE alongside rising rates indicates a bond bear market. > 130 = significant bond stress.                              |
| US Dollar Index (DXY)                         | Bloomberg / daily              | Real-time | None — DXY is the global FX gauge                                    | USD strengthens in global downturns (risk-off) and weakens in global Goldilocks. Rising DXY in risk-off = consistent; rising DXY + rising global PMIs = anomaly. |
| Goldman Sachs FCI (US)                        | Goldman Sachs / daily          | Real-time | UK / EZ / JP variants                                                | Composite of equity prices, credit spreads, real rates, exchange rates. Tight FCI = stimulative; loose FCI = restrictive. Leads economic activity by 3–6 months. |
| Bloomberg US FCI                              | Bloomberg / daily              | Real-time | UK / EZ Bloomberg variants                                           | Alternative to GS FCI. Most useful as rate-of-change signal rather than absolute level.                                                                         |
| EM Currencies (EMFX Index)                    | Bloomberg / daily              | Real-time | None — EMFX is by construction multi-country                         | EM currencies as global risk-appetite proxy. EM weakness + falling commodities = global risk-off; EM strength + rising commodities = global risk-on.            |

### 5.3.1 Pipeline Composite Candidates (Financial-Conditions-Tagged)

The data pipeline's financial-conditions composites are well developed. Strong candidates for validation include: US_Cr2 (US High-Yield Credit Spread, the 5-regime classifier with thresholds at 800/500/400/300 bps); US_Cr1, US_Cr3, US_Cr4 (IG spread, HY-IG, HY vs Treasuries); US_V1 (VIX term structure: VIX3M − VIX, with inversion as a crisis signal); US_V2 (MOVE / VIX); EU_Cr2 (Euro HY); UK_Cr1 (GBP credit); FX_1, FX_2 (dollar and FX momentum). The 5-regime US_Cr2 in particular is an example of a literature-derived classifier (the 800-500-400-300 thresholds come from academic work on credit spreads) that the pipeline already implements; the master plan retains this kind of classifier as an indicator-level enrichment to a candidate that itself enters the production engine on the basis of validation.

## 5.4 Monetary Policy Indicators

Monetary policy indicators measure central-bank stance and its market implications. They are the foundation of the inflation axis and a strong driver of the financial-conditions modulation; they earn a separate pillar in this catalogue because their interpretation is structurally different from headline inflation or growth indicators.

| Indicator                          | Source / Frequency        | Lag       | Regional analogues                                          | Interpretation                                                                                                                                                  |
|------------------------------------|---------------------------|-----------|-------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Federal Funds Rate (effective)     | Fed / 8 meetings per year | Same day  | BoE Bank Rate, ECB Deposit Rate, BoJ Policy Rate, PBoC LPR | Foundational Tier-1 indicator. Direction and pace of hiking / cutting cycles set regime trajectory with 18-month lag to real economy. Rate vs Taylor estimate is restrictiveness. |
| Real Federal Funds Rate            | Calculated / monthly      | Monthly   | UK / EZ / JP / CN analogues                                  | Nominal FFR minus Core PCE. Real rate is the true measure of monetary restrictiveness. Real rates above 2% historically associated with recession risk in 12–18 months.            |
| Fed Funds Futures (implied path)   | CME / daily               | Real-time | UK SONIA futures, EZ ESTR futures                            | Market-implied probability distribution of future policy rates. Forward-looking signal; dovish repricing = risk-on signal.                                                          |
| Taylor Rule Gap                    | Calculated / quarterly    | Quarterly | UK / EZ / JP / CN analogues with appropriate parameterisation | Gap between Taylor Rule policy rate and actual rate. Positive = stimulative; negative = restrictive. Calibrates regime-transition timing.                                            |
| Global Monetary Policy Tracker     | JP Morgan / BIS / monthly | Monthly   | Same source for global aggregate                             | Net proportion of major central banks in hiking vs cutting mode. > 70% hiking = global tightening; relevant for EM external financing conditions.                                   |

## 5.5 The Risk-Appetite / Sentiment Layer

A supplementary layer above the four pillars captures cross-asset sentiment dynamics. It is not a primary regime axis (Section 2.7 explains why) but it is a meaningful modulator of tilt confidence within the macro frame. The Mueller-Glissmann (Goldman Sachs) risk-appetite indicator is the best-known proprietary measure in this category; its public-data proxies are constructed from data already in the pipeline.

The proxies:

- **HY−IG spread ratio.** Z-scored over 156 weeks. Low reading = compressed risk premium (late-cycle complacency); high reading = stressed risk premium (recovery / early-cycle entry point).
- **Equity Risk Premium (earnings yield minus 10y real yield).** A low ERP relative to history signals equity risk premia compressed; a high ERP signals elevated risk compensation. The Shiller PE inverse is the simplest approximation.
- **VIX term-structure slope.** Contango (VIX9D < VIX3M < spot or similar) signals market calm; backwardation signals near-term stress. A composite of spot VIX, VIX3M, and VIX9D captures the term structure.

These three proxies together approximate the full GS risk-appetite indicator without requiring the proprietary subscription. They enter the candidate pool for the Financial Conditions pillar in the validation framework; if they pass validation, they appear as confidence modulators on the regime call rather than as primary classifiers.

## 5.6 Composite Aggregation: from Library to Pillar Score

The library above is the *candidate pool*. The production regime engine consumes only those indicators that have passed Section 8B validation. The aggregation from individual validated indicators to the per-region Growth and Inflation pillar scores is specified mathematically in Section 3.5; the indicator-library role here is to populate the candidate pool from which the validation selects.

Two operational notes on the candidate pool. First, the candidate pool is *deliberately wide*. The Section 8B validation is statistical and walk-forward; including a candidate that fails validation is essentially free (the validation simply rejects it), whereas excluding a candidate that would have passed validation is potentially expensive (the production engine misses a signal it could have used). The library above is therefore a maximalist starting point; the production engine that emerges from validation is a strict subset.

Second, the candidate pool *evolves over time*. As the data pipeline expands its coverage (Stage C and Stage E in the data pipeline forward plan; the long-run data layer ingestion in master plan Phase 0), new candidates enter the pool. As validation is re-run periodically (Section 8B specifies the cadence), the production set is refreshed. The library in this section is therefore a snapshot of the candidate pool at the time of writing; the operational system maintains the pool dynamically.

## 5.7 Cycle-Timing Classification

Each candidate indicator carries a literature-derived cycle-timing classification — Leading, Coincident, or Lagging — based on the academic and practitioner consensus on its lead time relative to the macroeconomic outturn. The classifications are summarised below for the principal indicators in the library; they are *priors* for the validation framework, not commitments. Where Section 8B validation produces a different classification (an indicator that the literature says is Leading but that fails the lead-time test in our hands), the validation classification supersedes the literature classification in the production engine.

| Cycle-timing class | Indicators (illustrative subset)                                                                                            | Typical lead / lag                              |
|--------------------|-----------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------|
| Leading            | Yield curve slopes (10y−2y, 10y−3m); M2 YoY; OECD CLI; LEI; SLOOS; building permits; NAHB; ISM New Orders; HY OAS; Fed Funds Futures path; US_G1 cyclicals/defensives; FX_CMD1 copper/gold; GL_PMI1 global PMI composite | 6–18 months ahead of macro outturn for macro Leading; 2–6 months for financial-conditions Leading |
| Coincident         | ISM Manufacturing PMI headline; ISM Services PMI; Consumer Confidence; Initial Jobless Claims (4-week MA); Industrial Production YoY; Retail Sales | Contemporaneous with macro outturn              |
| Lagging            | Nonfarm Payrolls; Real GDP advance estimate; Core CPI YoY; Core PCE YoY; Atlanta Fed GDPNow (intra-quarter coincident, full-quarter lagging) | 0–3 months behind macro outturn                 |

The data pipeline's existing classification of its 92 composites is heavily Leading-tilted (90 of 92 are tagged Leading, 2 Coincident, 0 Lagging). This reflects the analytical purpose of the pipeline — forward-looking regime indicator construction — and is the right composition for the candidate pool. The validation framework will, however, find that some of the pipeline composites the literature classifies as Leading are actually Coincident in our hands; the production cycle-timing classification reflects the validation outcome rather than the prior classification.

## 5.8 Per-Region Coverage Matrix

The catalogue above is most complete for the United States (where the data is deepest) and progressively thinner for the other priority regions. The current state of regional coverage in the data pipeline, summarised against the literature-derived demand-side library, is:

| Pillar             | US             | UK             | Eurozone        | Japan           | China          |
|--------------------|----------------|----------------|-----------------|-----------------|----------------|
| Growth             | Comprehensive  | Thin (LEI gap) | Comprehensive   | Partial         | Partial        |
| Inflation          | Comprehensive  | Comprehensive  | Comprehensive   | Partial         | Partial        |
| Financial Cond.    | Comprehensive  | Partial        | Comprehensive   | Partial         | Thin           |
| Monetary Policy    | Comprehensive  | Comprehensive  | Comprehensive   | Comprehensive   | Partial        |

The "Thin" and "Partial" entries are gaps that Phase 0 of the master forward plan addresses. Specifically, the UK Growth column is the largest single regional gap (the literature library lists 8 UK Growth indicators against the data pipeline's current coverage of approximately 0–2; the ONS API integration referenced in the data pipeline's §3.1 closes this gap with monthly UK GDP, IoP, retail sales, and labour-market series). The Japan and China columns are constrained by free-data availability and may settle at "Partial" permanently for some pillars. The matrix above is the starting point for Phase 0; the per-region availability test produces a refined matrix as its primary output.

\newpage
